import { Component, signal } from '@angular/core';
import { PetComponent } from "../../../components/pet-component/pet-component";
import { UserPet } from '../../../models/Resource';

@Component({
  selector: 'app-pet-animate',
  imports: [PetComponent],
  templateUrl: './pet-animate.html',
  styleUrl: './pet-animate.css',
})
export class PetAnimate {
  pet = signal<UserPet>({
    name:'Pochi',
    url:'https://res.cloudinary.com/dhvmcbbdi/image/upload/v1782985847/cG9jaGk_e0y7ez.png',
    pet_animations:[
      { name:'idle1',
        frame_h:'64px',
        frame_w:'64px',
        index_y:0,
        index_x_count:6,
        is_idle:true,
        seconds:'1s',
        scale:200
      },
      { name:'standing',
        frame_h:'64px',
        frame_w:'64px',
        index_y:1,
        index_x_count:3,
        is_idle:true,
        seconds:'0.7s',
        scale:200
      },
      { name:'dying',
        frame_h:'64px',
        frame_w:'64px',
        index_y:2,
        index_x_count:1,
        is_idle:false,
        seconds:'0.7s',
        scale:200
      },
      { name:'sleeping',
        frame_h:'64px',
        frame_w:'64px',
        index_y:3,
        index_x_count:4,
        is_idle:false,
        seconds:'2s',
        scale:200
      },
      { name:'stretching',
        frame_h:'64px',
        frame_w:'64px',
        index_y:4,
        index_x_count:10,
        is_idle:true,
        seconds:'3s',
        scale:200
      },
      { name:'running1',
        frame_h:'64px',
        frame_w:'64px',
        index_y:5,
        index_x_count:6,
        is_idle:false,
        seconds:'0.8s',
        scale:200
      },
      { name:'running2',
        frame_h:'64px',
        frame_w:'64px',
        index_y:6,
        index_x_count:12,
        is_idle:false,
        seconds:'0.8s',
        scale:200
      },
      { name:'box1',
        frame_h:'64px',
        frame_w:'64px',
        index_y:7,
        index_x_count:12,
        is_idle:true,
        seconds:'2s',
        scale:200
      },
      { name:'box2',
        frame_h:'64px',
        frame_w:'64px',
        index_y:8,
        index_x_count:10,
        is_idle:true,
        seconds:'2s',
        scale:200
      },
      { name:'box3',
        frame_h:'64px',
        frame_w:'64px',
        index_y:9,
        index_x_count:12,
        is_idle:true,
        seconds:'2s',
        scale:200
      },
      { name:'crying',
        frame_h:'64px',
        frame_w:'64px',
        index_y:10,
        index_x_count:4,
        is_idle:false,
        seconds:'1s',
        scale:200
      },
      { name:'dancing',
        frame_h:'64px',
        frame_w:'64px',
        index_y:11,
        index_x_count:4,
        is_idle:false,
        seconds:'0.7s',
        scale:200
      },
      { name:'sitting',
        frame_h:'64px',
        frame_w:'64px',
        index_y:12,
        index_x_count:8,
        is_idle:true,
        seconds:'1s',
        scale:200
      },
      { name:'surprise',
        frame_h:'64px',
        frame_w:'64px',
        index_y:13,
        index_x_count:2,
        is_idle:true,
        seconds:'1s',
        scale:200
      },
      { name:'rolling',
        frame_h:'64px',
        frame_w:'64px',
        index_y:14,
        index_x_count:4,
        is_idle:true,
        seconds:'0.7s',
        scale:200
      },
      { name:'boring',
        frame_h:'64px',
        frame_w:'64px',
        index_y:16,
        index_x_count:5,
        is_idle:false,
        seconds:'1s',
        scale:200
      },
    ],
  })
  animationName = signal<string>('running1');
}
